<?php

namespace App\Filament\Resources\AssetResource\Pages;

use App\Domain\Assets\Models\Asset;
use App\Domain\Assets\Services\AssetTagService;
use App\Filament\Resources\AssetResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;
use Illuminate\Validation\ValidationException;

class CreateAsset extends CreateRecord
{
    protected static string $resource = AssetResource::class;

    protected bool $autoGeneratedTag = false;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $this->autoGeneratedTag = empty($data['asset_tag']);

        if ($this->autoGeneratedTag) {
            $data['asset_tag'] = app(AssetTagService::class)->generate($data['category_id'] ?? null);
        }

        return $data;
    }

    protected function handleRecordCreation(array $data): Model
    {
        $attempts = 0;

        while (true) {
            try {
                /** @var Asset $model */
                $model = static::getModel()::create($data);

                return $model;
            } catch (QueryException $exception) {
                if ($this->isDuplicateAssetTagError($exception) && $this->autoGeneratedTag && $attempts < 5) {
                    $attempts++;
                    $data['asset_tag'] = app(AssetTagService::class)->generate($data['category_id'] ?? null);

                    continue;
                }

                if ($this->isDuplicateAssetTagError($exception)) {
                    throw ValidationException::withMessages([
                        'asset_tag' => 'Asset tag already exists.',
                    ]);
                }

                throw $exception;
            }
        }
    }

    protected function isDuplicateAssetTagError(QueryException $exception): bool
    {
        $errorInfo = $exception->errorInfo ?? [];
        $errorCode = $errorInfo[1] ?? null;

        if ((int) $errorCode !== 1062) {
            return false;
        }

        $message = strtolower($exception->getMessage());

        return str_contains($message, 'assets_asset_tag_unique')
            || str_contains($message, 'asset_tag_unique')
            || str_contains($message, 'asset_tag');
    }
}
